[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ajishio"
version = "0.1.0"
description = "A stripped-down pygame-based 2D game engine for creating 2D games."
requires-python = ">=3.14"
dependencies = [
    "pygame-ce",
    "websockets>=16.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["ajishio*"]

[tool.ruff]
exclude = [
    "src/ajishio/pyqtree.py",
]

[tool.basedpyright]
stubPath = "src/stubs"
ignore = [
    "src/ajishio/pyqtree.py",
]
