[project]
name = "ajishio-workspace"
version = "0.1.0"
description = "Workspace for the Ajishio 2D game engine and demo projects."
requires-python = ">=3.14"
dependencies = [
    "pygame-ce",
]

[tool.uv.sources]
ajishio = { workspace = true }
ajishio-demo-projects = { workspace = true }

[tool.uv.workspace]
members = [
    "ajishio",
    "demo_projects",
]

