[project]
name = "ajishio-workspace"
version = "0.1.0"
description = "Workspace for the Ajishio 2D game engine and demo projects."
requires-python = ">=3.14"
dependencies = [
    "ajishio",
    "pygbag>=0.9.3",
]

[tool.uv.workspace]
members = [
    "demo_projects",
]

[tool.uv.sources]
ajishio = { path = "./ajishio", editable = true }

[dependency-groups]
dev = [
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-literate-nav>=0.6.3",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
    "ruff>=0.15.11",
    "snakeviz>=2.2.2",
]

[tool.ruff]
exclude = [
    "**/_web_build/",
    "ajishio/src/ajishio/pyqtree.py",
]

[tool.basedpyright]
ignore = [
    "**/_web_build/",
    "ajishio/src/ajishio/pyqtree.py",
]
