# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Actor",
    "EntitiesResource",
    "Entity",
    "User",
    "UserLockout",
    "UserLogin",
    "UserLoginFailure",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


@dataclasses.dataclass()
class Actor:
    entity_id: int
    user_id: int


@dataclasses.dataclass()
class EntitiesResource:
    entity_id: int
    level_required: int


@dataclasses.dataclass()
class Entity:
    id_: int
    entity_type: int
    added: datetime.datetime
    last_updated: datetime.datetime
    x_position: int
    y_position: int
    entity_name: str


@dataclasses.dataclass()
class User:
    id_: int
    username: str
    password_hash: str
    created_at: datetime.datetime
    last_login: datetime.datetime | None
    last_updated: datetime.datetime


@dataclasses.dataclass()
class UserLockout:
    id_: int
    user_id: int
    added: datetime.datetime
    expiration: datetime.datetime | None


@dataclasses.dataclass()
class UserLogin:
    id_: int
    user_id: int
    login_time: datetime.datetime
    ip_address: str


@dataclasses.dataclass()
class UserLoginFailure:
    id_: int
    user_id: int
    added: datetime.datetime
    ip_address: str
