# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: query.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "count_users",
    "create_user",
    "create_user_lockout",
    "create_user_login",
    "create_user_login_failure",
    "delete_user_lockout_by_user_id",
    "get_user",
    "get_user_by_username",
    "get_user_lockouts_by_user_id",
    "list_users",
    "update_user_last_login",
    "update_user_last_updated",
    "update_user_password_hash",
)

import aiosqlite
import datetime
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import sqlite3

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

from demo_projects.moonlapse.server.db import models


def _adapt_datetime(val: datetime.datetime) -> str:
    return val.isoformat()


def _convert_datetime(val: bytes) -> datetime.datetime:
    return datetime.datetime.fromisoformat(val.decode())


aiosqlite.register_adapter(datetime.datetime, _adapt_datetime)

aiosqlite.register_converter("datetime", _convert_datetime)
aiosqlite.register_converter("timestamp", _convert_datetime)


GET_USER: typing.Final[str] = """-- name: GetUser :one
SELECT id, username, password_hash, created_at, last_login, last_updated FROM users WHERE id = ?
"""

LIST_USERS: typing.Final[str] = """-- name: ListUsers :many
SELECT id, username, password_hash, created_at, last_login, last_updated FROM users ORDER BY id LIMIT ? OFFSET ?
"""

GET_USER_BY_USERNAME: typing.Final[str] = """-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, last_login, last_updated FROM users WHERE username = ?
"""

CREATE_USER: typing.Final[str] = """-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?)
RETURNING id, username, password_hash, created_at, last_login, last_updated
"""

UPDATE_USER_LAST_LOGIN: typing.Final[str] = """-- name: UpdateUserLastLogin :one
UPDATE users SET last_login = CURRENT_TIMESTAMP, last_updated = CURRENT_TIMESTAMP WHERE id = ?
RETURNING id, username, password_hash, created_at, last_login, last_updated
"""

COUNT_USERS: typing.Final[str] = """-- name: CountUsers :one
SELECT COUNT(*) FROM users
"""

UPDATE_USER_PASSWORD_HASH: typing.Final[str] = """-- name: UpdateUserPasswordHash :one
UPDATE users SET password_hash = ?, last_updated = CURRENT_TIMESTAMP WHERE id = ?
RETURNING id, username, password_hash, created_at, last_login, last_updated
"""

UPDATE_USER_LAST_UPDATED: typing.Final[str] = """-- name: UpdateUserLastUpdated :one
UPDATE users SET last_updated = CURRENT_TIMESTAMP WHERE id = ?
RETURNING id, username, password_hash, created_at, last_login, last_updated
"""

CREATE_USER_LOGIN: typing.Final[str] = """-- name: CreateUserLogin :one
INSERT INTO user_logins (user_id, ip_address) VALUES (?, ?)
RETURNING id, user_id, login_time, ip_address
"""

CREATE_USER_LOGIN_FAILURE: typing.Final[str] = """-- name: CreateUserLoginFailure :one
INSERT INTO user_login_failures (user_id, ip_address) VALUES (?, ?)
RETURNING id, user_id, added, ip_address
"""

CREATE_USER_LOCKOUT: typing.Final[str] = """-- name: CreateUserLockout :one
INSERT INTO user_lockouts (user_id, expiration) VALUES (?, ?)
RETURNING id, user_id, added, expiration
"""

GET_USER_LOCKOUTS_BY_USER_ID: typing.Final[str] = """-- name: GetUserLockoutsByUserId :many
SELECT id, user_id, added, expiration FROM user_lockouts WHERE user_id = ?
"""

DELETE_USER_LOCKOUT_BY_USER_ID: typing.Final[str] = """-- name: DeleteUserLockoutByUserId :exec
DELETE FROM user_lockouts WHERE user_id = ?
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: aiosqlite.Connection,
        sql: str,
        decode_hook: collections.abc.Callable[[sqlite3.Row], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: aiosqlite.Cursor | None = None
        self._iterator: collections.abc.AsyncIterator[sqlite3.Row] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._args)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor: aiosqlite.Cursor | None = await self._conn.execute(self._sql, self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def get_user(conn: aiosqlite.Connection, *, id_: int) -> models.User | None:
    row = await (await conn.execute(GET_USER, (id_,))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


def list_users(conn: aiosqlite.Connection, *, limit: int, offset: int) -> QueryResults[models.User]:
    def _decode_hook(row: sqlite3.Row) -> models.User:
        return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])

    return QueryResults(conn, LIST_USERS, _decode_hook, limit, offset)


async def get_user_by_username(conn: aiosqlite.Connection, *, username: str) -> models.User | None:
    row = await (await conn.execute(GET_USER_BY_USERNAME, (username,))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


async def create_user(conn: aiosqlite.Connection, *, username: str, password_hash: str) -> models.User | None:
    row = await (await conn.execute(CREATE_USER, (username, password_hash))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


async def update_user_last_login(conn: aiosqlite.Connection, *, id_: int) -> models.User | None:
    row = await (await conn.execute(UPDATE_USER_LAST_LOGIN, (id_,))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


async def count_users(conn: aiosqlite.Connection) -> int | None:
    row = await (await conn.execute(COUNT_USERS)).fetchone()
    if row is None:
        return None
    return row[0]


async def update_user_password_hash(conn: aiosqlite.Connection, *, password_hash: str, id_: int) -> models.User | None:
    row = await (await conn.execute(UPDATE_USER_PASSWORD_HASH, (password_hash, id_))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


async def update_user_last_updated(conn: aiosqlite.Connection, *, id_: int) -> models.User | None:
    row = await (await conn.execute(UPDATE_USER_LAST_UPDATED, (id_,))).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], username=row[1], password_hash=row[2], created_at=row[3], last_login=row[4], last_updated=row[5])


async def create_user_login(conn: aiosqlite.Connection, *, user_id: int, ip_address: str) -> models.UserLogin | None:
    row = await (await conn.execute(CREATE_USER_LOGIN, (user_id, ip_address))).fetchone()
    if row is None:
        return None
    return models.UserLogin(id_=row[0], user_id=row[1], login_time=row[2], ip_address=row[3])


async def create_user_login_failure(conn: aiosqlite.Connection, *, user_id: int, ip_address: str) -> models.UserLoginFailure | None:
    row = await (await conn.execute(CREATE_USER_LOGIN_FAILURE, (user_id, ip_address))).fetchone()
    if row is None:
        return None
    return models.UserLoginFailure(id_=row[0], user_id=row[1], added=row[2], ip_address=row[3])


async def create_user_lockout(conn: aiosqlite.Connection, *, user_id: int, expiration: datetime.datetime | None) -> models.UserLockout | None:
    row = await (await conn.execute(CREATE_USER_LOCKOUT, (user_id, expiration))).fetchone()
    if row is None:
        return None
    return models.UserLockout(id_=row[0], user_id=row[1], added=row[2], expiration=row[3])


def get_user_lockouts_by_user_id(conn: aiosqlite.Connection, *, user_id: int) -> QueryResults[models.UserLockout]:
    def _decode_hook(row: sqlite3.Row) -> models.UserLockout:
        return models.UserLockout(id_=row[0], user_id=row[1], added=row[2], expiration=row[3])

    return QueryResults(conn, GET_USER_LOCKOUTS_BY_USER_ID, _decode_hook, user_id)


async def delete_user_lockout_by_user_id(conn: aiosqlite.Connection, *, user_id: int) -> None:
    await conn.execute(DELETE_USER_LOCKOUT_BY_USER_ID, (user_id,))
