import ajishio as aj
from typing import ClassVar, Protocol
import demo_projects.moonlapse.shared.packets.clientbound as clientbound


class ManagerLike(Protocol):
    client: aj.GameNetClient

    def log(self, message: str, color: aj.Color) -> None: ...
    def set_client_id(self, id: int) -> None: ...
    def get_client_id(self) -> int | None: ...


class State(Protocol):
    NAME: ClassVar[str]

    def on_enter(self) -> None: ...
    def on_exit(self) -> None: ...
    def handle_packet(self, p: clientbound.ClientboundPacket) -> State | None: ...
    def handle_text_input(self, text: str) -> None: ...
