from __future__ import annotations

import ajishio as aj
from typing import ClassVar, Protocol

import demo_projects.moonlapse.shared.packets.clientbound as clientbound
from demo_projects.moonlapse.client.world import World


class ManagerLike(Protocol):
    client: aj.GameNetClient
    world: World | None

    def log(self, message: str, color: aj.Color) -> None: ...
    def set_client_id(self, id: int) -> None: ...
    def get_client_id(self) -> int | None: ...
    def enter_world(self) -> None: ...
    def leave_world(self) -> None: ...


class State(Protocol):
    NAME: ClassVar[str]

    def on_enter(self) -> None: ...
    def on_exit(self) -> None: ...
    def handle_packet(self, p: clientbound.ClientboundPacket) -> State | None: ...
    def handle_text_input(self, text: str) -> None: ...
