[project]
name = "ajishio-demo-projects"
version = "0.1.0"
description = "Example games demonstrating how to use the Ajishio 2D game engine."
requires-python = ">=3.14"
dependencies = [
    "ajishio",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["demo_projects*"]
exclude = ["demo_projects.moonlapse*"]

[tool.basedpyright]
exclude = [
    "**/*generated*",
    "**/db/query.py",
    "**/db/models.py",
    "**/db/__init__.py",
]

[tool.ruff]
exclude = [
    "**/*generated*",
    "**/db/query.py",
    "**/db/models.py",
    "**/db/__init__.py",
]

